acc <- read.csv("zaimu.csv",header = TRUE)
deltasales <- subset(acc$sales,acc$year>2000) - subset(acc$sales,acc$year<2022)
deltasales <- data.frame(deltasales)
acc <- acc[c(-1),]
names(deltasales) <- c("delta.sales")
acc <- cbind(acc,deltasales)
accruals <- data.frame(acc$net.income-acc$ex.revenue+acc$ex.loss-acc$cf)
names(accruals) <- c("accruals")
acc <- cbind(acc,accruals)
eventtime <- 2012
accbefore <- subset(acc,acc$year<eventtime)
accafter <- subset(acc,acc$year>=eventtime)
jones <- lm(accbefore$accruals ~ accbefore$delta.sales+accbefore$tangible.assets)
intce <- jones$coefficients["(Intercept)"]
salcoef <- jones$coefficients["accbefore$delta.sales"]
tangcoef <- jones$coefficients["accbefore$tangible.assets"]
nda <- acc$delta.sales*salcoef+acc$tangible.assets+intce
ndadata <- data.frame(nda)
names(ndadata) <- c("NDA")
acc <- cbind(acc,ndadata)
da <- data.frame(acc$accruals-nda)
names(da) <- c("discreationary")
acc <- cbind(acc,da)
dabefore <- subset(acc$discreationary,acc$year<eventtime)
daafter <- subset(acc$discreationary,acc$year>=eventtime)
hp1ttest <- t.test(daafter, alternative = c("two.sided"),mu = 0, paired = FALSE, var.equal = FALSE, conf.level = 0.95)
hp1pvalue <- data.frame(hp1ttest$p.value)
acc <- cbind(acc,hp1pvalue)
hp2ttest1 <- t.test(dabefore, alternative = c("two.sided"),mu = 0, paired = FALSE, var.equal = FALSE, conf.level = 0.95)
hp2pvalue1 <- data.frame(hp2ttest1$p.value)
acc <- cbind(acc,hp2pvalue1)
hp2ttest2 <- t.test(daafter, dabefore, alternative = c("less"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
hp2pvalue2 <- data.frame(hp2ttest2$p.value)
acc <- cbind(acc,hp2pvalue2)
write.csv(x = acc, file = "zaimu/result/sancooru.csv")
